import type { Metadata } from "next";
import { IBM_Plex_Sans } from 'next/font/google';
import "./globals.css";

const ibm = IBM_Plex_Sans({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ibm' // Add CSS variable support
});

export const metadata: Metadata = {
  title: "MedicalHunt | Neet Results Analysis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ibm.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}